# Generated by Django 5.2.5 on 2025-08-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='estagio',
            field=models.TextField(default='Em andamento', max_length=120),
            preserve_default=False,
        ),
    ]
